# Generated by Django 6.0 on 2026-01-20 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loginattempt',
            unique_together={('email', 'ip_address')},
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='loginattempt',
            name='last_attempt',
        ),
    ]
