# Generated by Django 6.0 on 2026-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_loginattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='last_attempt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
